config/routes.rb
Rails.application.routes.draw do
  namespace :admin do
    get '', to: 'dashboard#index', as: '/'
     resources :categories
     resources :users
  end

end

app/models/categorie.rb
class Categorie < ActiveRecord::Base

	validates :name,  presence: true, length: { maximum: 25 }, uniqueness: true


end

app/models/user.rb
class User < ActiveRecord::Base


  before_save { self.email = email.downcase }
  validates :first_name, presence: true, length: { maximum: 10 }
  validates :last_name, presence: true, length: { maximum: 10 }
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence:   true,
                    format:     { with: VALID_EMAIL_REGEX },
                    uniqueness: { case_sensitive: false }
  validates :phone, presence: true, length: { maximum: 10 }
  validates :state, presence: true, length: { maximum: 10 }

end

app/controllers/admin/categories_controller.rb
class Admin::CategoriesController < ApplicationController
  
  def index
  	@category = Categorie.all
  end

  def show
  	@category = Categorie.find(params[:id])
  end

  def new
  	@category = Categorie.new
  end
  
  def create
    @category = Categorie.new(cat_params)    
    if @category.save
      flash[:success] = "Category is added successfully!"
      redirect_to [:admin, @category]
    else
      render 'new'
    end
  end

  def edit
    @category = Categorie.find(params[:id])
  end

  def update
    @category = Categorie.find(params[:id])
    if @category.update_attributes(cat_params)
      flash[:success] = "Category is updated successfully!"
      redirect_to [:admin_category]
    else
      render 'edit'
    end
  end

  def destroy
    Categorie.find(params[:id]).destroy
    flash[:success] = "Category deleted successfully"
    redirect_to [:admin_categories]
  end

  private
    def cat_params
       params.require(:categorie).permit(:name)
    end
 

end

app/controllers/admin/dashboard_controller.rb
class Admin::DashboardController < ApplicationController
  def index
  end
end

app/controllers/admin/users_controller.rb
class Admin::UsersController < ApplicationController
  
  def index
  	@user = User.all
  end

  def show
  	@user = User.find(params[:id])
  end

  def new
  	@user = User.new
  end
  
  def create
    @user = User.new(user_params)    
    if @user.save
      flash[:success] = "User is added successfully!"
      redirect_to [:admin, @user]
    else
      render 'new'
    end
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    if @user.update_attributes(user_params)
      flash[:success] = "User is updated successfully!"
      redirect_to [:admin_user]
    else
      render 'edit'
    end
  end

  def destroy
    User.find(params[:id]).destroy
    flash[:success] = "User deleted successfully"
    redirect_to [:admin_categories]
  end

  private
    def user_params
       params.require(:user).permit(:first_name,:last_name,:email,:phone,:state)
    end
 

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/helpers/admin/dashboard_helper.rb
module Admin::DashboardHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/admin/categories/edit.html.erb
<h1>Update Category</h1> 
 <%= form_for([:admin, @category]) do |c| %>
<table>
   
    	<%= render 'shared/error_messages' ,object: c.object %>
		<tr>
		     <td> <%= c.label :name %></td>
		     <td> <%= c.text_field :name %></td>
		</tr>
		
	    <tr>
	     	<td> <%= c.submit "Update new category", class: "btn btn-large btn-primary" %></td>
	     	<td><%= link_to 'Cancel', admin_categories_path, class: "btn btn-info" %></td>
	    </tr>
    
</table>  
<% end %>

app/views/admin/categories/index.html.erb
<h1>Course List</h1> <br>

<%= link_to 'Add New Category', new_admin_category_path, class: "btn btn-info" %>&nbsp;&nbsp;
 <%= link_to 'Dashboard(Home)', admin_path, class: "btn btn-info" %>
 <br><br>  
<% if @category.count == 0 %>
<%= "No record presents" %>
<% else %>
<table border=0 cellspaceing="5" cellpadding="5">
	<tr>
		<td>Name</td>
		<td></td>
		<td></td>
	</tr>
	<% @category.each do |category| %>
		<tr>
			<td><%= link_to category.name , [:admin, category] %></td>
			<td><%= link_to "Edit", edit_admin_category_path(category) %></td>
			<td><%= link_to "delete", [:admin, category], method: :delete, data: { confirm: 'Are you sure?' } %>	
			
		</tr>
	<% end %>
</table>
<% end %>	
 <br><br>
 
  

app/views/admin/categories/new.html.erb
<h1>Add New Course</h1> 
 <%= form_for([:admin, @category]) do |c| %>
<table>
   
    	<%= render 'shared/error_messages' ,object: c.object %>
		<tr>
		     <td> <%= c.label :name %></td>
		     <td> <%= c.text_field :name %></td>
		</tr>
		
	    <tr>
	     	<td> <%= c.submit "Create new category", class: "btn btn-large btn-primary" %></td>
	     	<td><%= link_to 'Cancel', admin_categories_path, class: "btn btn-info" %></td>
	    </tr>
    
</table>  
<% end %>

app/views/admin/categories/show.html.erb
<h1>Show Categories</h1> <br><br>

<table border=0 cellspaceing="5">
	<tr>
		<td>Name</td><td>:</td><td><%= @category.name %></td>
	</tr>	
	
</table>	

<br>
<%= link_to 'Back', admin_categories_path, class: "btn btn-info" %>
<br>

app/views/admin/dashboard/index.html.erb
<h1>Administration</h1> 
<ul> 
	<li><%= link_to 'Manage Categories' , admin_categories_path  %></li> 
	<li><%= link_to 'Manage Users' , admin_users_path  %></li>
</ul> 

app/views/admin/users/edit.html.erb
<h1>UpdateUser</h1> 
 <%= form_for([:admin, @user]) do |c| %>
<table>
   
    	<%= render 'shared/error_messages' ,object: c.object %>
		<tr>
		     <td> <%= c.label :first_name %></td>
		     <td> <%= c.text_field :first_name %></td>
		</tr>

		<tr>
		     <td> <%= c.label :last_name %></td>
		     <td> <%= c.text_field :last_name %></td>
		</tr>

		<tr>
		     <td> <%= c.label :email %></td>
		     <td> <%= c.text_field :email %></td>
		</tr>

		<tr>
		     <td> <%= c.label :phone %></td>
		     <td> <%= c.text_field :phone %></td>
		</tr>
		
		<tr>
		     <td> <%= c.label :state %></td>
		     <td> <%= c.text_field :state %></td>
		</tr>

	    <tr>
	     	<td> <%= c.submit "Update user", class: "btn btn-large btn-primary" %></td>
	     	<td><%= link_to 'Cancel', admin_users_path, class: "btn btn-info" %></td>
	    </tr>
    
</table>  
<% end %>

app/views/admin/users/index.html.erb
<h1>User List</h1> <br>

<%= link_to 'Add New User', new_admin_user_path, class: "btn btn-info" %>&nbsp;&nbsp;
 <%= link_to 'Dashboard(Home)', admin_path, class: "btn btn-info" %>
 <br><br>  
<% if @user.count == 0 %>
<%= "No record presents" %>
<% else %>
<table border=0 cellspaceing="5" cellpadding="5">
	<tr>
		<td>Name</td>
		<td>Email</td>
		<td>Phone</td>
		<td>State</td>
	</tr>
	<% @user.each do |user| %>
		<tr>
			<td><%= link_to (user.first_name + " " + user.last_name) , [:admin, user] %></td>
			<td><%= user.email  %></td>
			<td><%= user.phone  %></td>
			<td><%= user.state  %></td>
			<td><%= link_to "Edit", edit_admin_user_path(user) %></td>
			<td><%= link_to "delete", [:admin, user], method: :delete, data: { confirm: 'Are you sure?' } %>	
			
		</tr>
	<% end %>
</table>
<% end %>	
 <br><br>
 
  

app/views/admin/users/new.html.erb
<h1>Add New User</h1> 
 <%= form_for([:admin, @user]) do |c| %>
<table>
   
    	<%= render 'shared/error_messages' ,object: c.object %>
		<tr>
		     <td> <%= c.label :first_name %></td>
		     <td> <%= c.text_field :first_name %></td>
		</tr>

		<tr>
		     <td> <%= c.label :last_name %></td>
		     <td> <%= c.text_field :last_name %></td>
		</tr>

		<tr>
		     <td> <%= c.label :email %></td>
		     <td> <%= c.text_field :email %></td>
		</tr>

		<tr>
		     <td> <%= c.label :phone %></td>
		     <td> <%= c.text_field :phone %></td>
		</tr>
		
		<tr>
		     <td> <%= c.label :state %></td>
		     <td> <%= c.text_field :state %></td>
		</tr>

	    <tr>
	     	<td> <%= c.submit "Create new user", class: "btn btn-large btn-primary" %></td>
	     	<td><%= link_to 'Cancel', admin_users_path, class: "btn btn-info" %></td>
	    </tr>
    
</table>  
<% end %>

app/views/admin/users/show.html.erb
<h1>Show User Detail</h1> <br><br>

<table border=0 cellspaceing="5">
	<tr>
		<td>Name</td><td>:</td><td><%= @user.first_name %> <%= @user.last_name %></td>
	</tr>	
	<tr>
		<td>Email</td><td>:</td><td><%= @user.email %></td>
	</tr>	
	<tr>
		<td>Phone</td><td>:</td><td><%= @user.phone %></td>
	</tr>	
	<tr>
		<td>State</td><td>:</td><td><%= @user.state %></td>
	</tr>	

	
</table>	

<br>
<%= link_to 'Back', admin_users_path, class: "btn btn-info" %>
<br>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>CaptiveOne</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<% if notice %>
  <p class="alert alert-success"><%= notice %></p>
<% end %>
<% if alert %>
  <p class="alert alert-danger"><%= alert %></p>
<% end %>

<% flash.each do |key, value| %>
  <div class="alert alert-<%= key %>"><%= value %></div>
<% end %>

<%= yield %>
<%= debug(params) if Rails.env.development? %>
</body>
</html>

app/views/shared/_error_messages.html.erb
<% if object.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-error">
      The form contains <%= pluralize(object.errors.count, "error") %>.
    </div>
    <ul>
    <% object.errors.full_messages.each do |msg| %>
      <li>* <%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>